// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

func (c *CollectorDef) ShouldComponentUpdateIntf(nextProps, prevState, nextState interface{}) bool {
	res := false

	{
		res = c.Props() != nextProps.(CollectorProps) || res
	}
	return res
}

// Props is an auto-generated proxy to the current props of Collector
func (c *CollectorDef) Props() CollectorProps {
	uprops := c.ComponentDef.Props()
	return uprops.(CollectorProps)
}

func (c CollectorProps) EqualsIntf(val interface{}) bool {
	return c == val.(CollectorProps)
}

var _ react.Equals = CollectorProps{}
