// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

func (t *TodoDef) ShouldComponentUpdateIntf(nextProps, prevState, nextState interface{}) bool {
	res := false

	{
		res = t.Props() != nextProps.(TodoProps) || res
	}
	return res
}

// Props is an auto-generated proxy to the current props of Todo
func (t *TodoDef) Props() TodoProps {
	uprops := t.ComponentDef.Props()
	return uprops.(TodoProps)
}

func (t TodoProps) EqualsIntf(val interface{}) bool {
	return t == val.(TodoProps)
}

var _ react.Equals = TodoProps{}
