// Template generated by reactGen

package main

import (
	"honnef.co/go/js/dom"
	r "myitcv.io/react"
)

//go:generate reactGen

var document = dom.GetWindow().Document()

func main() {

	domTarget := document.GetElementByID("app")

	r.Render(App(), domTarget)
}
